config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products
  resource :cart, only: [:show] do
    get 'finish_order', to: 'cart#finish_order', as: :finish_order
    post 'add_random', to: 'cart#add_random', as: :add_random
    post 'add/:product_id', to: 'cart#add', as: :add_to
    delete 'remove/:product_id', to: 'cart#remove', as: :remove_from
    delete 'clear', to: 'cart#clear', as: :clear
  end
  root "cart#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :initialize_cart, only: [:show, :add_random, :remove, :clear, :finish_order]

  def show
    @cart_items = @cart.map do |product_id, quantity|
      product = Product.find(product_id)
      { product: product, quantity: quantity }
    end
  end

  def remove
    @product = Product.find(params[:product_id])
    @cart.delete(@product.id.to_s)
    save_cart
    redirect_to cart_path, notice: "Товар удален из корзины."
  end

  def clear
    @cart.clear
    save_cart
    redirect_to cart_path, notice: "Корзина очищена."
  end

  def finish_order
    @cart.clear
    session[:cart] = nil
    redirect_to cart_path, notice: "Заказ оформлен."
  end

  def add_random
    Product.all.each do |product|
      quantity = rand(1..3)
      product_id = product.id.to_s
      if @cart.key?(product_id)
        @cart[product_id] += quantity
      else
        @cart[product_id] = quantity
      end
    end

    save_cart
    redirect_to cart_path, notice: "Тестовые данные установлены."
  end

  private

  def initialize_cart
    @cart = session[:cart] ||= {}
  end

  def save_cart
    session[:cart] = @cart
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when 'notice' then 'success'
    when 'alert' then 'danger'
    else flash_type.to_s
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def print_price(price)
    price.to_i.to_s + ' ₽'
  end

  def formatted_amount(cart_items)
    total = cart_items.sum { |item| item[:product].price * item[:quantity] }
    number_to_currency(total, unit: '₽')
  end
end

app/views/cart/show.html.erb
<div class="m-5" data-controller="cart">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="title">Корзина</h1>
    <% if @cart_items.any? %>
      <%= link_to 'Очистить корзину', clear_cart_path, data: { turbo_method: :delete, turbo_confirm: "Вы уверены, что хотите очистить корзину?" }, class: "btn text-grey clean-cart-button" %>
    <% end %>
  </div>

  <% if @cart_items.empty? %>
    <div class="mt-5 d-flex flex-column align-items-center">
      <%= image_tag "empty.png", size: "48x48" %>
      <h5 class="mt-3 title">В корзине нет товаров</h5>
      <p class="product-name text-grey">Добавьте тестовый товар</p>
      <%= button_to 'Добавить тестовые данные', add_random_cart_path, method: :post, class: "btn custom-button mt-3" %>
    </div>
  <% else %>
    <div class="cart-items me-3">
      <% @cart_items.each do |item| %>
        <div class="cart-item row py-3 border-bottom align-items-center">
          <div class="product-image col-2">
            <% if item[:product].image.attached? %>
              <%= image_tag item[:product].image, size: "100x100" %>
            <% end %>
          </div>
          <div class="col-4">
            <h5 class="product-name m-0"><%= item[:product].name %></h5>
          </div>
          <div class="product-quantity col-3 d-flex flex-column align-items-end">
            <div class="input-group">
              <div class="input-group-prepend">
                <button type="button" class="btn btn-outline-secondary" data-action="cart#decrease" data-cart-target="quantityControl">
                  <i class="bi bi-dash"></i>
                </button>
              </div>
              <input class="form-control text-center" value="<%= item[:quantity] %>" min="1" data-cart-target="quantity" data-action="change->cart#handleQuantityChange">
              <div class="input-group-append">
                <button type="button" class="btn btn-outline-secondary" data-action="cart#increase" data-cart-target="quantityControl">
                  <i class="bi bi-plus"></i>
                </button>
              </div>
            </div>
          </div>
          <div class="col-3 d-flex flex-column align-items-end">
            <%= link_to remove_from_cart_path(product_id: item[:product].id), data: { turbo_method: :delete, turbo_confirm: "Вы уверены, что хотите удалить этот товар из корзины?" }, class: "text-grey mb-2" do %>
              <i class="bi bi-trash"></i>
            <% end %>
            <h5 class="product-price" data-cart-target="price" data-price-per-unit="<%= item[:product].price %>" data-quantity="<%= item[:quantity] %>"><%= print_price(item[:product].price * item[:quantity]) %></h5>
          </div>
        </div>
      <% end %>
    </div>

      <div class="summary mt-4 p-4">
        <div class="d-flex justify-content-between">
          <h5 class="quantity-text">
            <span id="totalQuantity" data-cart-target="totalQuantity">
              <%= @cart_items.sum { |item| item[:quantity] } %>
            </span> товаров на сумму
          </h5>
          <span class="product-price" data-cart-target="totalAmount"><%= formatted_amount(@cart_items) %></span>
          </span>
        </div>

        <label for="discountRange" class="form-label mt-2 quantity-text">Передвигая слайдер, укажите сумму скидки</label>
        <span class="float-end mt-2 text-green product-price" data-cart-target="discountAmount">0</span>
        <input type="range" class="form-range mt-4" id="discountRange" min="0" max="1000" value="0" data-action="input->cart#updateDiscount" data-cart-target="discountRange">

        <hr class="mt-4">
        <div class="d-flex justify-content-between mt-4">
          <h5 class="product-price">Сумма заказа:</h5>
          <h5 class="fw-bold" data-cart-target="finalAmount"><%= formatted_amount(@cart_items) %></h5>
        </div>
      </div>
    </div>
    <div class="m-5">
      <%= button_to 'Оформить', finish_order_cart_path, method: :get, class: "btn custom-button w-100" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopCart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid mx-5">
        <a class="navbar-brand" href="#">
          <%= image_tag 'logo.png', alt: 'Logo', width: '150', height: '36' %>
        </a>
      </div>
    </nav>

    <div class="container mt-4 mx-5">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= bootstrap_class_for(type) %> alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    </div>

    <div class="container mx-5">
      <%= yield %>
    </div>
  </body>
</html>